### ISSUE TITLE
Exceso de facha.

### ISSUE THREAD

**Issue by valenosa** [pdepjm/2024-tp0-presentacion-Matehdez#2]
<div align="center">

![text (1)](https://github.com/pdepjm/2024-tp0-presentacion-Matehdez/assets/83839175/40a7d81a-07bf-429f-a0d4-8f91404eb84c)

Me parece bastante `fuera de lugar` subir un TP0 como el tuyo.  

La realidad es que se torna bastante `molesto` ver como algunas personas suben fotos tan facheras como las tuyas.

Entiendo que estés `orgulloso` de tu `facha`, pero no me parece correcto que `presumas` ante los demás, simplemente es de `mal gusto`. 

¿Siquiera tenes la licencia para manejar ese

![2024-03-23-Exceso-de-facha-](https://github.com/pdepjm/2024-tp0-presentacion-Matehdez/assets/83839175/115a51e3-3f25-4c8d-9710-986c29a5e368)

<img src="https://i.pinimg.com/474x/30/72/fa/3072fa6a948778d229c642d13177488f.jpg" width = 309px>

<img src="https://pa1.aminoapps.com/6749/439399eab2476c10a24bbff8599795f0a927828f_hq.gif" width = 309px>

**Comment by mateonhernandez** [comment]
**Gracias** por tus comentarios buen hombre. 

La verdad creo que ninguna respuesta estará a la altura de semejante obra de arte como la tuya, asi que te voy a responder con una frase de los Simpson **muy importante** para la vida:

> La suma de las raíces cuadradas de dos lados de un triángulo isósceles es igual a la raíz cuadrada lado restante.”

 - [Homero](https://www.youtube.com/watch?v=1SgbhqIOVNU).
